name: Base-Test
env:
  APP_NAME  : "Get-Local-IP"
  PKG_NAME  : "get-local-ip-ver-${{ github.sha }}"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  initial_testing:
    runs-on: ubuntu-latest
    needs: [Linter-Test]

    steps:
      - uses: actions/checkout@v2

      - name: Print ENV
        run: |
          echo "App name: ${{ env.APP_NAME }}"
          echo "Pkg name: ${{ env.PKG_NAME }}"

      - name: List folder data
        run: ls -la


  run_script:
    runs-on: ubuntu-latest
    needs: [initial_testing]

    steps:
      - uses: actions/checkout@v2

      - name: Run script
        run: |
          bash ./get-local-ip.sh

